Repository paketo-buildpacks/cpython, pull requests merged in 2022-10, with the labels that each got.

#424 Ensure that integration tests only use dependencies for the specified stack
  integration/default_test.go
  integration/init_test.go
  integration/layer_reuse_test.go
Labels: semver:patch

#428 Use Standard Dependency Workflow
  .github/.syncignore
  .github/workflows/jammy-dependencies.yml
  .github/workflows/update-dependencies-from-metadata.yml
  .github/workflows/update-dependencies.yml
  dependency/Makefile
  dependency/actions/compile/README.md
  dependency/actions/compile/action.yml
  dependency/actions/compile/bionic.Dockerfile
  dependency/actions/compile/entrypoint
  dependency/actions/compile/jammy.Dockerfile
  dependency/compile/action.yml
  dependency/compile/compile.sh
  dependency/find-new-versions/action.yml
  dependency/find-new-versions/entrypoint/.gitignore
  dependency/find-new-versions/entrypoint/common.go
  dependency/find-new-versions/entrypoint/go.mod
  dependency/find-new-versions/entrypoint/go.sum
  dependency/find-new-versions/entrypoint/main.go
  dependency/prep-commit/action.yml
  dependency/prep-commit/entrypoint/.gitignore
  dependency/prep-commit/entrypoint/go.mod
  dependency/prep-commit/entrypoint/main.go
  dependency/retrieval/go.mod
  dependency/retrieval/go.sum
  dependency/retrieval/main.go
Labels: semver:patch

#443 Add dependency tests
  dependency/Makefile
  dependency/test/README.md
  dependency/test/fixtures/server.py
  dependency/test/test.sh
Labels: semver:patch

#442 Set PYTHONPYCACHEPREFIX to /tmp during build phase.
  README.md
  build.go
  build_test.go
  integration/default_test.go
Labels: semver:minor

#451 Revert deps bumps
  build.go
  build_test.go
  buildpack.toml
  constants.go
  integration/layer_reuse_test.go
  integration/testdata/default_app/server.py
Labels: semver:patch

#450 Add `OpenSSL` support into `CPython` compilation (and ensure compilation tests check for SSL linking)
  dependency/actions/compile/bionic.Dockerfile
  dependency/actions/compile/entrypoint.sh
  dependency/actions/compile/jammy.Dockerfile
  dependency/test/README.md
  dependency/test/bionic.Dockerfile
  dependency/test/entrypoint.sh
  dependency/test/jammy.Dockerfile
  dependency/test/test.sh
Labels: status/blocked, semver:patch
